#!/bin/sh
# preinst script for mongodb
#
# see: dh_installdeb(1)

# create a mongodb group and user
echo " * Please run manually /usr/bin/thp-disable.sh script before the starting TokuMXSE daemon"
echo " * To disable Transparent Huge Pages kernel feature"
if ! getent passwd mongod >/dev/null 2>&1; then
	adduser --system --no-create-home mongod
    addgroup --system mongod
    adduser mongod mongod
fi

chown -R mongod:mongod /var/lib/mongodb
chown -R mongod:mongod /var/log/mongodb

